FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY apps/frontend/package*.json ./

# Install dependencies
RUN npm ci

# Copy app source
COPY apps/frontend/ .

# Build
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
